# -*- coding: utf-8 -*-
"""Handwritting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_Rrdo8t4eT2ddFaqR5aJF8p6cZ5pPBC
"""

import cv2
from matplotlib import pyplot as plt
from google.colab import drive
drive.mount('/content/drive')
path1 = '/content/drive/My Drive/pcd_dataset/handwritting.jpg'
image = cv2.imread(path1)
img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.imshow(img)
plt.show()

#Transformasi Biner
import numpy as np
image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
h,w = image.shape

gr = np.zeros([h,w], dtype=np.uint8)
t = 60
for y in range(0, h):
  for x in range(0, w):
    v = int(img[y,x,0])
    if v < t:
      gr[y,x] = 0
    elif v >= t:
      gr[y, x] = 255


plt.imshow(gr,'gray')
plt.show()